spring:
    application:
        name: authentication
    datasource:
        driver-class-name: org.postgresql.Driver
        
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect